import { getLevels } from "../../../api/levels";
import { getHomeServices } from "../../../api/home-services";
import Home from "../../../components/home/Home";

export const metadata = {
  title: "IBook | صفحة الرئيسية للطالب ",
  description: "Generated by IBook",
};

const page = async () => {
  const levels = await getLevels();
  const services = await getHomeServices();

  return <Home levels={levels.data.levels} services={services} />;
};

export default page;
