import { getBookByStudentDetails } from '../../../api/book-by-student';
import QuizReportsPage from '../../../components/QuizzReportsPage/QuizzReportsPage'
import { getCookie } from '../../../Utils/get-cookie-server'

export const metadata = {
  title: "IBook | تقارير الاختبارات",
  description: "Generated by IBook",
};

const page = async () => {
  const cookie = await getCookie('ibook-user')
  const userData = JSON.parse(cookie)
  const ALL_BOOKS = await getBookByStudentDetails(userData)
  const allBooks = ALL_BOOKS.data.books.filter(book => book.status === true)
  return (
    <QuizReportsPage allBooks={allBooks} />
  )
}

export default page