import Reports from '../../../components/Reports/Reports'
import { getBookByStudentDetails } from '../../../api/book-by-student-details';
import { getCookie } from '../../../Utils/get-cookie-server';

export const metadata = {
  title: "IBook | تقارير الكتب",
  description: "Generated by IBook",
};
const page = async () => {
  const cookie = await getCookie('ibook-user')
  const userData = JSON.parse(cookie)
  const ALL_BOOKS = await getBookByStudentDetails(userData)
  const allBooks = ALL_BOOKS.data.books.filter(book => book.status === true)

  return (
    <Reports allBooks={allBooks} />
  )
}

export default page