import Login from "../../../components/Login/Login";

export const metadata = {
  title: "IBook | تسجيل الدخول",
  description: "Generated by IBook",
};
function page() {
  return (
    <Login />
  );
}


export default page;
