import { getBookByStudentId } from "../../../../api/book-by-student-id";
import { getLevels } from "../../../../api/levels";
import { getSemister } from "../../../../api/semister";
import { getStudentCountry } from "../../../../api/student-country";
import { getSudentInfoById } from "../../../../api/student-info-by-id";
import Student from "../../../../components/Student/Student";

export async function generateMetadata({ params }) {
  const id = (await params).id
  return {
    title: `IBook | الابن رقم ${id}`,
    description: "Generated by IBook",
  }
}

const page = async ({ params }) => {
  const id = (await params).id
  const studentResponse = await getSudentInfoById(id);
  const ALL_BOOKS = await getBookByStudentId(id);
  const country = await getStudentCountry();
  const semestersRsponse = await getSemister();
  const levelsRsponse = await getLevels();
  
  return (
    <Student
      studentId={id}
      studentData={studentResponse.data}
      allBooks={ALL_BOOKS.data.books.filter(book => book.status === true)}
      studentCountry={country.data}
      semesters={semestersRsponse.data.semesters}
      levels={levelsRsponse.data.levels}
    />
  )
}

export default page;
