import { getBooks } from "../../../../api/books";
import Books from "../../../../components/Books/Books";

export const metadata = {
  title: "IBook | الكتب الدراسية",
  description: "Generated by IBook",
};

const BooksPage = async ({ searchParams }) => {
  const { level, semester } = await searchParams;
  const booksData = await getBooks(level, semester);
  const books = booksData?.data.books || [];
  
  return <Books books={books} />;
};

export default BooksPage;
