import { getLevels } from '../../../api/levels';
import { getSemister } from '../../../api/semister';
import { getStudentCountry } from '../../../api/student-country';
import AddStudent from '../../../components/AddStudent/AddStudent'

export const metadata = {
  title: "IBook | اضافة طالب",
  description: "Generated by IBook",
};

const page = async () => {
  let studentCountry = await getStudentCountry();
  let semesters = await getSemister();
  let levels = await getLevels();

  return (
    <AddStudent
      studentCountry={studentCountry.data}
      semesters={semesters.data.semesters}
      levels={levels.data.levels}
    />
  )
}

export default page
