import { getStudentsOfParent } from "../../../api/parent-get-child";
import { addStudentsOfParent } from "../../../api/parent-add-child";
import Parent from '../../../components/Parent/Parent';

export const metadata = {
  title: "IBook | صفحة الرئيسية لولي الامر",
  description: "Generated by IBook",
  icons: [
    {
      url: "/book.png",
      href: "/book.png"
    }
  ]
};

const page = async () => {

  const parentData = await getStudentsOfParent();
  const canAddData = await addStudentsOfParent();

  return (
    <Parent canAddData={canAddData} parentData={parentData} />
  );
};


export default page;
