import { getSemister } from "../../../api/semister";
import Levels from "../../../components/Levels/Levels";

export const metadata = {
  title: "IBook | الفصول الدراسية",
  description: "Generated by IBook",
};

const LevelsPage = async ({ searchParams }) => {
  const { level } = await searchParams;
  const levelId = level || null;
  const semestersData = await getSemister();
  const semesters = semestersData?.data.semesters || [];

  return <Levels semesters={semesters} levelId={levelId} />;
};

export default LevelsPage;
